// <auto-generated />
using System;
using Aponus_Web_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AponusWebAPI.Migrations
{
    [DbContext(typeof(AponusContext))]
    [Migration("20221221080535_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AI")
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aponus_Web_API.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PRODUCT_ID")
                        .UseCollation("Modern_Spanish_CI_AI");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CATEGORY_ID")
                        .UseCollation("Modern_Spanish_CI_AI");

                    b.Property<decimal?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasColumnName("PRICE")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("ProductDescriptionDn")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_DESCRIPTION_DN");

                    b.Property<int?>("ProductDescriptionInsideDiameter")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_DESCRIPTION_INSIDE_DIAMETER");

                    b.Property<string>("ProductDescriptionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PRODUCT_DESCRIPTION_NAME")
                        .UseCollation("Modern_Spanish_CI_AI");

                    b.Property<int?>("ProductDescriptionOutsideDiameter")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_DESCRIPTION_OUTSIDE_DIAMETER");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("ProductId")
                        .HasName("PK_PRODUCTS_1");

                    b.HasIndex("CategoryId");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ProductCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CATEGORY_ID")
                        .UseCollation("Modern_Spanish_CI_AI");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CATEGORY_DESCRIPTION")
                        .UseCollation("Modern_Spanish_CI_AI");

                    b.HasKey("CategoryId")
                        .HasName("PK_Table_1");

                    b.ToTable("PRODUCT_CATEGORIES", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Product", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
