// <auto-generated />
using System;
using Aponus_Web_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AponusWebAPI.Migrations
{
    [DbContext(typeof(AponusContext))]
    [Migration("20240912011537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AI")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aponus_Web_API.Models.ArchivosMovimientosStock", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("ID_MOVIMIENTO");

                    b.Property<string>("HashArchivo")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HASH_ARCHIVO");

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.Property<string>("MimeType")
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("MIME_TYPE");

                    b.Property<string>("PathArchivo")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("PATH");

                    b.HasKey("IdMovimiento", "HashArchivo");

                    b.HasIndex("IdEstadoMovimiento");

                    b.ToTable("ARCHIVOS_STOCK", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ComponentesDescripcion", b =>
                {
                    b.Property<int>("IdDescripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_DESCRIPCION");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDescripcion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdDescripcion");

                    b.ToTable("COMPONENTES_DESCRIPCION", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ComponentesDetalle", b =>
                {
                    b.Property<string>("IdInsumo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_INSUMO");

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ALTURA");

                    b.Property<decimal?>("Diametro")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DIAMETRO");

                    b.Property<int?>("DiametroNominal")
                        .HasColumnType("int")
                        .HasColumnName("DIAMETRO_NOMINAL");

                    b.Property<decimal?>("Espesor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ESPESOR");

                    b.Property<string>("IdAlmacenamiento")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ID_ALMACENAMIENTO");

                    b.Property<int>("IdDescripcion")
                        .HasColumnType("integer")
                        .HasColumnName("ID_DESCRIPCION");

                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasDefaultValueSql("1");

                    b.Property<string>("IdFraccionamiento")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ID_FRACCIONAMIENTO");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LONGITUD");

                    b.Property<int?>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("PERFIL");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("PESO");

                    b.Property<string>("Tolerancia")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TOLERANCIA");

                    b.HasKey("IdInsumo")
                        .HasName("PK_ID_INSUMO");

                    b.HasIndex("IdEstadoMovimiento");

                    b.ToTable("COMPONENTES_DETALLE", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Compras", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_COMPRA")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_HORA");

                    b.Property<int>("IdEstadoCompra")
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_COMPRA");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("ID_PROVEEDOR");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<decimal?>("SaldoCancelado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SALDO_CANCELADO");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SALDO_TOTAL");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdEstadoCompra");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("COMPRAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ComprasDetalles", b =>
                {
                    b.Property<int>("IdCompra")
                        .HasColumnType("int")
                        .HasColumnName("ID_COMPRA");

                    b.Property<string>("IdInsumo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_INSUMO");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CANTIDAD");

                    b.HasKey("IdCompra", "IdInsumo");

                    b.HasIndex("IdInsumo");

                    b.ToTable("COMPRAS_DETALLE", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.CuotasVentas", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CUOTA")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuota"));

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_PAGO");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_VENCIMIENTO");

                    b.Property<int>("IdEstadoCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_CUOTA")
                        .HasDefaultValueSql("1");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("ID_VENTA");

                    b.Property<decimal>("Monto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MONTO")
                        .HasDefaultValueSql("0.00");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_CUOTA");

                    b.HasKey("IdCuota");

                    b.HasIndex("IdEstadoCuota");

                    b.HasIndex("IdVenta");

                    b.ToTable("CUOTAS_VENTAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Entidades", b =>
                {
                    b.Property<int>("IdEntidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_ENTIDAD");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEntidad"));

                    b.Property<string>("Altura")
                        .HasColumnType("text")
                        .HasColumnName("ALTURA");

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("APELLIDO");

                    b.Property<string>("Barrio")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("BARRIO");

                    b.Property<string>("Calle")
                        .HasColumnType("text")
                        .HasColumnName("CALLE");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("CIUDAD");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text")
                        .HasColumnName("CODIGO_POSTAL");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FECHA_REGISTRO");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("(1)");

                    b.Property<string>("IdFiscal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ID_FISCAL");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("ID_TIPO");

                    b.Property<string>("IdUsuarioRegistro")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_USUARIO_REGISTRO");

                    b.Property<string>("Localidad")
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("LOCALIDAD");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("NombreClave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NOMBRE_CLAVE");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("PAIS");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("PROVINCIA");

                    b.Property<string>("Telefono1")
                        .HasColumnType("text")
                        .HasColumnName("TELEFONO_1");

                    b.Property<string>("Telefono2")
                        .HasColumnType("text")
                        .HasColumnName("TELEFONO_2");

                    b.Property<string>("Telefono3")
                        .HasColumnType("text")
                        .HasColumnName("TELEFONO_3");

                    b.HasKey("IdEntidad");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdTipo");

                    b.HasIndex("IdUsuarioRegistro");

                    b.ToTable("ENTIDADES", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EntidadesCategorias", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_CATEGORIA")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE_CATEGORIA");

                    b.HasKey("IdCategoria");

                    b.ToTable("ENTIDADES_CATEGORIAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EntidadesTipos", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_TIPO")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipo"));

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("IdTipo");

                    b.ToTable("ENTIDADES_TIPOS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EntidadesTiposCategorias", b =>
                {
                    b.Property<int>("idTipoEntidad")
                        .HasColumnType("int")
                        .HasColumnName("ID_TIPO");

                    b.Property<int>("IdCategoriaEntidad")
                        .HasColumnType("int")
                        .HasColumnName("ID_CATEGORIA");

                    b.HasKey("idTipoEntidad", "IdCategoriaEntidad");

                    b.HasIndex("IdCategoriaEntidad");

                    b.ToTable("ENTIDADES_TIPOS_CATEGORIAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosArchivosMovimientosStock", b =>
                {
                    b.Property<byte>("IdEstadoMovimiento")
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("ESTADOS_ARCHIVOS_MOVIMIENTOS_STOCK", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosComponentesDetalles", b =>
                {
                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoMovimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("EstadosComponentesDetalle");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosCompras", b =>
                {
                    b.Property<int>("IdEstadoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_COMPRA")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoCompra"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<int>("IdEstadoMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO");

                    b.HasKey("IdEstadoCompra");

                    b.ToTable("ESTADOS_COMPRAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosCuotasVentas", b =>
                {
                    b.Property<int>("IdEstadoCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_CUOTA")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoCuota"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.HasKey("IdEstadoCuota");

                    b.ToTable("ESTADOS_CUOTAS_VENTAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosMovimientosStock", b =>
                {
                    b.Property<int?>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("IdEstadoMovimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<byte?>("IdEstadoPropio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO_PROPIO")
                        .HasDefaultValueSql("1");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("ESTADOS_MOVIMIENTOS_STOCK", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosProductos", b =>
                {
                    b.Property<byte>("IdEstadoMovimiento")
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("EstadosProducto");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosProductosComponentes", b =>
                {
                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoMovimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("EstadosProductosComponente");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosProductosDescripciones", b =>
                {
                    b.Property<byte>("IdEstadoMovimiento")
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("ESTADOS_PRODUCTOS_DESCRIPCIONES", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosSuministrosMovimientosStock", b =>
                {
                    b.Property<byte>("IdEstadoMovimiento")
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("ESTADOS_SUMINISTROS_MOVIMIENTOS_STOCK", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosTiposProductos", b =>
                {
                    b.Property<byte>("IdEstadoMovimiento")
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.HasKey("IdEstadoMovimiento");

                    b.ToTable("ESTADOS_PRODUCTOS_TIPOS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosVentas", b =>
                {
                    b.Property<int>("IdEstadoVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_VENTA")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoVenta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("ID_ESTADO");

                    b.HasKey("IdEstadoVenta");

                    b.ToTable("ESTADOS_VENTAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.MediosPago", b =>
                {
                    b.Property<int>("IdMedioPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_MEDIO_PAGO")
                        .HasAnnotation("SqlServer:Identity", "1,1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedioPago"));

                    b.Property<string>("CodigoMPago")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CODIGO_MPAGO");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("ID_ESTADO");

                    b.HasKey("IdMedioPago");

                    b.ToTable("MEDIOS_PAGO", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.PagosCompras", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PAGO")
                        .HasColumnOrder(2)
                        .HasAnnotation("SqlServer:Identity", "1,1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<int?>("CantidadCuotas")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD_CUOTAS");

                    b.Property<int?>("CantidadCuotasCanceladas")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD_CUOTAS_CANCELADAS");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int")
                        .HasColumnName("ID_COMPRA");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("int")
                        .HasColumnName("ID_MEDIO_PAGO");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SUBTOTAL");

                    b.Property<decimal?>("SubtotalCancelado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SUBTOTAL_CANCELADO");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdMedioPago");

                    b.ToTable("PAGOS_COMPRAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.PagosVentas", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PAGO")
                        .HasColumnOrder(2)
                        .HasAnnotation("SqlServer:Identity", "1,1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA");

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("int")
                        .HasColumnName("ID_MEDIO_PAGO");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("ID_VENTA");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MONTO");

                    b.HasKey("IdPago");

                    b.HasIndex("IdMedioPago");

                    b.HasIndex("IdVenta");

                    b.ToTable("PAGOS_VENTAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Producto", b =>
                {
                    b.Property<string>("IdProducto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<int?>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CANTIDAD")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("DiametroNominal")
                        .HasColumnType("integer")
                        .HasColumnName("DIAMETRO_NOMINAL");

                    b.Property<int>("IdDescripcion")
                        .HasColumnType("integer")
                        .HasColumnName("ID_DESCRIPCION");

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.Property<string>("IdTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ID_TIPO");

                    b.Property<decimal?>("PorcentajeGanancia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PORCENTAJE_GANANCIA");

                    b.Property<decimal?>("PrecioFinal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRECIO_FINAL");

                    b.Property<decimal?>("PrecioLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasColumnName("PRECIO_LISTA")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Tolerancia")
                        .HasColumnType("text")
                        .HasColumnName("TOLERANCIA");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdDescripcion");

                    b.HasIndex("IdEstadoMovimiento");

                    b.HasIndex("IdTipo");

                    b.ToTable("PRODUCTOS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ProductosDescripcion", b =>
                {
                    b.Property<int>("IdDescripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_DESCRIPCION");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDescripcion"));

                    b.Property<string>("DescripcionProducto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.HasKey("IdDescripcion");

                    b.HasIndex("IdEstadoMovimiento");

                    b.ToTable("PRODUCTOS_DESCRIPCION", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ProductosTipo", b =>
                {
                    b.Property<string>("IdTipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ID_TIPO");

                    b.Property<string>("DescripcionTipo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.HasKey("IdTipo")
                        .HasName("PK_Table_1");

                    b.HasIndex("IdEstadoMovimiento");

                    b.ToTable("PRODUCTOS_TIPOS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Productos_Componentes", b =>
                {
                    b.Property<string>("IdProducto")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<string>("IdComponente")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_COMPONENTE");

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CANTIDAD");

                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LONGITUD");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PESO");

                    b.HasKey("IdProducto", "IdComponente")
                        .HasName("PK_PRODUCTOS_COMPONENTES");

                    b.HasIndex("IdEstadoMovimiento");

                    b.ToTable("PRODUCTOS_COMPONENTES", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Productos_Tipos_Descripcion", b =>
                {
                    b.Property<string>("IdTipo")
                        .HasColumnType("text")
                        .HasColumnName("ID_TIPO");

                    b.Property<int?>("IdDescripcion")
                        .HasColumnType("integer")
                        .HasColumnName("ID_DESCRIPCION");

                    b.HasKey("IdTipo", "IdDescripcion");

                    b.ToTable("PRODUCTOS_TIPOS_DESCRIPCION", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.StockInsumos", b =>
                {
                    b.Property<string>("IdInsumo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_INSUMO");

                    b.Property<decimal?>("Granallado")
                        .HasColumnType("decimal")
                        .HasColumnName("GRANALLADO");

                    b.Property<decimal?>("Moldeado")
                        .HasColumnType("decimal")
                        .HasColumnName("MOLDEADO");

                    b.Property<decimal?>("Pendiente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PENDIENTE");

                    b.Property<decimal?>("Pintura")
                        .HasColumnType("decimal")
                        .HasColumnName("PINTURA");

                    b.Property<decimal?>("Proceso")
                        .HasColumnType("decimal")
                        .HasColumnName("PROCESO");

                    b.Property<decimal?>("Recibido")
                        .HasColumnType("decimal")
                        .HasColumnName("RECIBIDO");

                    b.HasKey("IdInsumo")
                        .HasName("PK_STOCK_INSUMOS");

                    b.ToTable("STOCK_INSUMOS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Stock_Movimientos", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_MOVIMIENTO");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<string>("CreadoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USUARIO_CREADO");

                    b.Property<string>("Destino")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DESTINO");

                    b.Property<DateTime>("FechaHoraCreado")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FECHA_HORA_CREADO");

                    b.Property<DateTime?>("FechaHoraUltimaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FECHA_HORA_ULTIMA_MODIFICACION");

                    b.Property<int>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.Property<int>("IdEntidad")
                        .HasColumnType("int")
                        .HasColumnName("ID_PROVEEDOR_DESTINO");

                    b.Property<int>("IdProveedorOrigen")
                        .HasColumnType("int")
                        .HasColumnName("ID_PROVEEDOR_ORIGEN");

                    b.Property<string>("ModificadoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USUARIO_MODIFICA");

                    b.Property<string>("Origen")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ORIGEN");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdEstadoMovimiento");

                    b.HasIndex("IdEntidad");

                    b.HasIndex("IdProveedorOrigen");

                    b.ToTable("Stock_Movimientos");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.SuministrosMovimientosStock", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .HasColumnType("int")
                        .HasColumnName("ID_MOVIMIENTO");

                    b.Property<string>("IdSuministro")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ID_SUMINISTRO");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CANTIDAD");

                    b.Property<byte>("IdEstadoMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Varbinary(1)")
                        .HasColumnName("ID_ESTADO")
                        .HasDefaultValueSql("1");

                    b.Property<decimal?>("ValorAnteriorDestino")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_ANTERIOR_DESTINO");

                    b.Property<decimal?>("ValorAnteriorOrigen")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_ANTERIOR_ORIGEN");

                    b.Property<decimal?>("ValorNuevoDestino")
                        .HasColumnType("numeric")
                        .HasColumnName("VALOR_NUEVO_DESTINO");

                    b.Property<decimal?>("ValorNuevoOrigen")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_NUEVO_ORIGEN");

                    b.HasKey("IdMovimiento", "IdSuministro");

                    b.HasIndex("IdEstadoMovimiento");

                    b.ToTable("SUMINISTROS_MOVIMIENTOS_STOCK", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Usuarios", b =>
                {
                    b.Property<string>("Usuario")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USUARIO");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CONTRASEÑA");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("ID_PERFIL");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CORREO");

                    b.HasKey("Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Ventas", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VENTA")
                        .HasAnnotation("SqlServer:Identity", "1, 1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_HORA");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<int>("IdEstadoVenta")
                        .HasColumnType("int")
                        .HasColumnName("ID_ESTADO_VENTA");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric")
                        .HasColumnName("SALDO_PENDIENTE");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstadoVenta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("VENTAS", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.VentasDetalles", b =>
                {
                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("ID_VENTA");

                    b.Property<string>("IdProducto")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CANTIDAD");

                    b.Property<int?>("Entregados")
                        .HasColumnType("integer")
                        .HasColumnName("ENTREGADOS");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRECIO");

                    b.HasKey("IdVenta", "IdProducto");

                    b.HasIndex("IdProducto");

                    b.ToTable("VENTAS_DETALLES", (string)null);
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ArchivosMovimientosStock", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosArchivosMovimientosStock", "ArchivosMovimientosStockNavigation")
                        .WithMany("ArchivosMovimientoStock")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Stock_Movimientos", "StockMovimiento")
                        .WithMany()
                        .HasForeignKey("IdMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivosMovimientosStockNavigation");

                    b.Navigation("StockMovimiento");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ComponentesDetalle", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosComponentesDetalles", "IdEstadoNavigation")
                        .WithMany("ComponentesDetalle")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Compras", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosCompras", "Estado")
                        .WithMany("compras")
                        .HasForeignKey("IdEstadoCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Entidades", "IdProveedor")
                        .WithMany("compras")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Usuarios", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("IdProveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ComprasDetalles", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.Compras", "Compra")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.ComponentesDetalle", "DetallesInsumo")
                        .WithMany("ComprasNavigation")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("DetallesInsumo");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.CuotasVentas", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosCuotasVentas", "EstadoCuota")
                        .WithMany("IdEstadoCuotaNavigation")
                        .HasForeignKey("IdEstadoCuota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Ventas", "Venta")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoCuota");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Entidades", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EntidadesCategorias", "CategoriaEntidad")
                        .WithMany("Entidades")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.EntidadesTipos", "TipoEntidad")
                        .WithMany("Entidades")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Usuarios", "UsuarioRegistro")
                        .WithMany("IdUsuarioRegistroNavigation")
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaEntidad");

                    b.Navigation("TipoEntidad");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EntidadesTiposCategorias", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EntidadesCategorias", "CategoriaEntidad")
                        .WithMany("TiposCategoriasNavigation")
                        .HasForeignKey("IdCategoriaEntidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.EntidadesTipos", "TipoEntidad")
                        .WithMany("TiposCategoriasNavigation")
                        .HasForeignKey("idTipoEntidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaEntidad");

                    b.Navigation("TipoEntidad");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.PagosCompras", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.Compras", "Compra")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.MediosPago", "MedioPago")
                        .WithMany("PagosComprasNavigation")
                        .HasForeignKey("IdMedioPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("MedioPago");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.PagosVentas", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.MediosPago", "MedioPago")
                        .WithMany("PagosVentasNavigation")
                        .HasForeignKey("IdMedioPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Ventas", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedioPago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Producto", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.ProductosDescripcion", "IdDescripcionNavigation")
                        .WithMany("StockInsumos")
                        .HasForeignKey("IdDescripcion")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTOS_PRODUCTOS_DESCRIPCION");

                    b.HasOne("Aponus_Web_API.Models.EstadosProductos", "IdEstadoNavigation")
                        .WithMany("StockInsumos")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.ProductosTipo", "IdTipoNavigation")
                        .WithMany("StockInsumos")
                        .HasForeignKey("IdTipo")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTOS_PRODUCTOS_TIPOS");

                    b.Navigation("IdDescripcionNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdTipoNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ProductosDescripcion", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosProductosDescripciones", "IdEstadoNavigation")
                        .WithMany("ProductosDescripcions")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ProductosTipo", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosTiposProductos", "IdEstadoNavigation")
                        .WithMany("ProductosTipos")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Productos_Componentes", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosProductosComponentes", "IdEstadoNavigation")
                        .WithMany("ProductosComponentes")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Stock_Movimientos", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosMovimientosStock", "estadoMovimiento")
                        .WithMany("movimientosStock")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Entidades", "IdProveedor")
                        .WithMany("MovimientosDestino")
                        .HasForeignKey("IdEntidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Entidades", "ProveedorOrigen")
                        .WithMany("MovimientosOrigen")
                        .HasForeignKey("IdProveedorOrigen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProveedor");

                    b.Navigation("ProveedorOrigen");

                    b.Navigation("estadoMovimiento");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.SuministrosMovimientosStock", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.EstadosSuministrosMovimientosStock", "EstadosSuministrosMovimientosStockNavigation")
                        .WithMany("SuministrosMovimientoStock")
                        .HasForeignKey("IdEstadoMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Stock_Movimientos", null)
                        .WithMany("Suministros")
                        .HasForeignKey("IdMovimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadosSuministrosMovimientosStockNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Ventas", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.Entidades", "Cliente")
                        .WithMany("ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.EstadosVentas", "Estado")
                        .WithMany("ventas")
                        .HasForeignKey("IdEstadoVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aponus_Web_API.Models.Usuarios", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.VentasDetalles", b =>
                {
                    b.HasOne("Aponus_Web_API.Models.Producto", "IdProductoNavigation")
                        .WithMany("Ventas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VENTAS_DETALLES_PRODUCTOS_ID_PRODUCTO");

                    b.HasOne("Aponus_Web_API.Models.Ventas", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ComponentesDetalle", b =>
                {
                    b.Navigation("ComprasNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Compras", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Entidades", b =>
                {
                    b.Navigation("MovimientosDestino");

                    b.Navigation("MovimientosOrigen");

                    b.Navigation("compras");

                    b.Navigation("ventas");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EntidadesCategorias", b =>
                {
                    b.Navigation("Entidades");

                    b.Navigation("TiposCategoriasNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EntidadesTipos", b =>
                {
                    b.Navigation("Entidades");

                    b.Navigation("TiposCategoriasNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosArchivosMovimientosStock", b =>
                {
                    b.Navigation("ArchivosMovimientoStock");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosComponentesDetalles", b =>
                {
                    b.Navigation("ComponentesDetalle");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosCompras", b =>
                {
                    b.Navigation("compras");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosCuotasVentas", b =>
                {
                    b.Navigation("IdEstadoCuotaNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosMovimientosStock", b =>
                {
                    b.Navigation("movimientosStock");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosProductos", b =>
                {
                    b.Navigation("StockInsumos");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosProductosComponentes", b =>
                {
                    b.Navigation("ProductosComponentes");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosProductosDescripciones", b =>
                {
                    b.Navigation("ProductosDescripcions");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosSuministrosMovimientosStock", b =>
                {
                    b.Navigation("SuministrosMovimientoStock");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosTiposProductos", b =>
                {
                    b.Navigation("ProductosTipos");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.EstadosVentas", b =>
                {
                    b.Navigation("ventas");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.MediosPago", b =>
                {
                    b.Navigation("PagosComprasNavigation");

                    b.Navigation("PagosVentasNavigation");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Producto", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ProductosDescripcion", b =>
                {
                    b.Navigation("StockInsumos");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.ProductosTipo", b =>
                {
                    b.Navigation("StockInsumos");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Stock_Movimientos", b =>
                {
                    b.Navigation("Suministros");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Usuarios", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("IdUsuarioRegistroNavigation");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Aponus_Web_API.Models.Ventas", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("DetallesVenta");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
